
const POSITION = 'POSITION';
const MOVEMENT = "MOVEMENT";
const SPRITE = "SPRITE";
const ANIMATION = "ANIMATION";
const PLAYER = "PLAYER";
const COLLISION = "COLLISION";
const TRANSITION = "TRANSITION";
const CHARACTER = "CHARACTER";
const ACTIONABLE = "ACTIONABLE";
const HITBOX = "HITBOX";
const HEALTH = "HEALTH";
const ITEMDROP = "ITEMDROP";
const ITEM = "ITEM";


export { ITEMDROP, ITEM, POSITION, MOVEMENT, SPRITE, ANIMATION, PLAYER, COLLISION, TRANSITION, ACTIONABLE, CHARACTER, HITBOX, HEALTH }