
const POSITION = 'POSITION';
const RIGIDBODY = "RIGIDBODY";
const SPRITE = "SPRITE";
const ANIMATION = "ANIMATION";
const PLAYER = "PLAYER";
const COLLISION = "COLLISION";
const TRANSITION = "TRANSITION";
const CHARACTER = "CHARACTER";
const ACTIONABLE = "ACTIONABLE";
const HITBOX = "HITBOX";
const HEALTH = "HEALTH";
const ITEMDROP = "ITEMDROP";
const ITEM = "ITEM";
const STATE = "STATE";


export { ITEMDROP, ITEM, POSITION, RIGIDBODY, SPRITE, ANIMATION, PLAYER, COLLISION, TRANSITION, ACTIONABLE, CHARACTER, HITBOX, HEALTH, STATE }