const RENDER_SYSTEM = "RENDER_SYSTEM"
const ANIMATION_SYSTEM = "ANIMATION_SYSTEM"
const COLLISION_SYSTEM = "COLLISION_SYSTEM"
const MOVEMENT_SYSTEM = "MOVEMENT_SYSTEM"
const TRANSITION_SYSTEM = "TRANSITION_SYSTEM"
const ACTIONABLE_SYSTEM = "ACTIONABLE_SYSTEM"
const HITBOX_SYSTEM = "HITBOX_SYSTEM"
const HEALTH_SYSTEM = "HEALTH_SYSTEM"
const ITEM_SYSTEM = "ITEM_SYSTEM"
const ITEMDROP_SYSTEM = "ITEM_SYSTEM"



export { RENDER_SYSTEM, ANIMATION_SYSTEM, COLLISION_SYSTEM, MOVEMENT_SYSTEM, TRANSITION_SYSTEM, ACTIONABLE_SYSTEM, ITEM_SYSTEM, ITEMDROP_SYSTEM, HITBOX_SYSTEM, HEALTH_SYSTEM }